# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f64337a369efd6c124be2d36bca51a759550f59168e4902555d38f174504d2fb07007bff231544f60e3adcae9c33db702b204cc03b4e4bb9c85d1c308472b251

test:
  secret_key_base: e4fce19e098ecadf28c6f306a131f13bb859f0fc25ee459d599efa2716e410236a7861d9cb838c21f7f70135d833be70c56187a4472659c2383cc0b4613041b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
